import { AsyncLocalStorage } from "node:async_hooks";
import pg from "pg";
import type { RunResult, SqlDriver } from "./driver.js";

/*
  The Postgres engine: the source of truth going forward. It starts from its own baseline
  (the schema as it stands after SQLite's migration chain) plus what multi-tenancy needs
  from day one: an orgs table and a dormant org_id on every tenant-owned row, defaulted to
  the single built-in org until real accounts arrive. Data types deliberately mirror the
  SQLite shapes (TEXT ISO timestamps, INTEGER 0/1 flags) so both engines behave identically
  during the cutover; a PG-only migration modernizes types once SQLite is gone.
*/

// COUNT(*) and friends come back as int8; the app expects numbers, and no table here will
// ever exceed 2^53 rows before this platform has a very different data layer.
pg.types.setTypeParser(20, (v) => Number(v));

const now = () => new Date().toISOString();

/** Translate `?` placeholders to Postgres's $1..$n. No string literal in this codebase's SQL contains a question mark. */
function dollar(sql: string): string {
  let n = 0;
  return sql.replace(/\?/g, () => `$${++n}`);
}

function sslConfig(): pg.PoolConfig["ssl"] {
  const mode = (process.env.ACP_PG_SSL || "").toLowerCase();
  if (mode === "disable") return undefined;
  if (mode === "no-verify") return { rejectUnauthorized: false };
  if (mode === "require") return { rejectUnauthorized: true };
  return undefined; // whatever the connection string says
}

export async function openPg(databaseUrl: string): Promise<{ driver: SqlDriver; pool: pg.Pool }> {
  const pool = new pg.Pool({ connectionString: databaseUrl, max: Number(process.env.PG_POOL_MAX || 10), ssl: sslConfig() });
  const txClient = new AsyncLocalStorage<pg.PoolClient>();
  const q = (sql: string, params: unknown[] = []) => {
    const client = txClient.getStore();
    return client ? client.query(dollar(sql), params) : pool.query(dollar(sql), params);
  };

  const driver: SqlDriver = {
    kind: "pg",
    async all<T>(sql: string, params: unknown[] = []) {
      return (await q(sql, params)).rows as T[];
    },
    async get<T>(sql: string, params: unknown[] = []) {
      return (await q(sql, params)).rows[0] as T | undefined;
    },
    async run(sql: string, params: unknown[] = []): Promise<RunResult> {
      return { changes: (await q(sql, params)).rowCount ?? 0 };
    },
    async exec(sql: string) {
      const client = txClient.getStore();
      if (client) await client.query(sql);
      else await pool.query(sql);
    },
    async transaction<T>(fn: () => Promise<T>): Promise<T> {
      const existing = txClient.getStore();
      if (existing) return fn(); // nested: join the open transaction
      const client = await pool.connect();
      try {
        await client.query("BEGIN");
        const out = await txClient.run(client, fn);
        await client.query("COMMIT");
        return out;
      } catch (err) {
        try {
          await client.query("ROLLBACK");
        } catch {
          /* connection gone */
        }
        throw err;
      } finally {
        client.release();
      }
    },
    async schemaVersion() {
      return (await pool.query("SELECT id, name, applied_at FROM schema_migrations ORDER BY id")).rows as { id: number; name: string; applied_at: string }[];
    },
    async close() {
      await pool.end();
    },
  };

  await migratePg(driver);
  return { driver, pool };
}

/* ------------------------------------------------------------------------------------------
   Postgres migrations, starting at 100 so they can never collide with SQLite's 1..6 chain.
   Only ever append.
------------------------------------------------------------------------------------------ */
const PG_MIGRATIONS: { id: number; name: string; up: (d: SqlDriver) => Promise<void> }[] = [
  {
    id: 100,
    name: "postgres baseline with orgs and dormant tenancy",
    up: async (d) => {
      await d.exec(`
CREATE TABLE IF NOT EXISTS orgs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  plan TEXT NOT NULL DEFAULT 'default',
  quotas TEXT,
  created_at TEXT NOT NULL
);
INSERT INTO orgs (id, name, created_at) VALUES (1, 'Default', '${now()}') ON CONFLICT (id) DO NOTHING;
SELECT setval(pg_get_serial_sequence('orgs', 'id'), GREATEST((SELECT MAX(id) FROM orgs), 1));

CREATE TABLE IF NOT EXISTS agent_profiles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  org_id BIGINT NOT NULL DEFAULT 1 REFERENCES orgs(id),
  key TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  description TEXT,
  provider_id TEXT,
  kind TEXT NOT NULL DEFAULT 'custom',
  capabilities TEXT,
  status TEXT NOT NULL DEFAULT 'active',
  configuration TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS conversations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  org_id BIGINT NOT NULL DEFAULT 1 REFERENCES orgs(id),
  title TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  last_message_at TEXT
);

CREATE TABLE IF NOT EXISTS tasks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  org_id BIGINT NOT NULL DEFAULT 1 REFERENCES orgs(id),
  platform TEXT NOT NULL,
  key TEXT NOT NULL,
  name TEXT NOT NULL,
  source TEXT NOT NULL DEFAULT 'registry',
  purpose TEXT,
  schedule TEXT,
  native_url TEXT,
  status TEXT,
  enabled INTEGER NOT NULL DEFAULT 1,
  meta TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  keywords TEXT,
  delivery TEXT,
  agent_id BIGINT REFERENCES agent_profiles(id) ON DELETE SET NULL,
  prompt TEXT,
  next_run TEXT,
  configuration TEXT,
  UNIQUE(platform, key)
);

CREATE TABLE IF NOT EXISTS messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  org_id BIGINT NOT NULL DEFAULT 1 REFERENCES orgs(id),
  text TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'needs_assignment',
  task_id BIGINT REFERENCES tasks(id) ON DELETE SET NULL,
  suggestions TEXT,
  routing TEXT,
  delivery_mode TEXT,
  delivered_at TEXT,
  acked_at TEXT,
  response TEXT,
  error TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  platform TEXT,
  conversation_id BIGINT REFERENCES conversations(id) ON DELETE CASCADE,
  steps TEXT,
  run_id BIGINT
);
CREATE INDEX IF NOT EXISTS messages_status ON messages(status, created_at DESC);
CREATE INDEX IF NOT EXISTS messages_conversation ON messages(conversation_id, created_at);
CREATE INDEX IF NOT EXISTS messages_org ON messages(org_id, created_at DESC);

CREATE TABLE IF NOT EXISTS runs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  org_id BIGINT NOT NULL DEFAULT 1 REFERENCES orgs(id),
  task_id BIGINT REFERENCES tasks(id) ON DELETE CASCADE,
  agent_id BIGINT REFERENCES agent_profiles(id) ON DELETE SET NULL,
  provider TEXT,
  kind TEXT NOT NULL DEFAULT 'external',
  trigger TEXT,
  message_id BIGINT REFERENCES messages(id) ON DELETE SET NULL,
  label TEXT,
  external_id TEXT,
  status TEXT NOT NULL,
  started_at TEXT,
  finished_at TEXT,
  summary TEXT,
  details TEXT,
  output_url TEXT,
  error TEXT,
  source TEXT NOT NULL,
  raw TEXT,
  created_at TEXT NOT NULL
);
ALTER TABLE messages ADD CONSTRAINT messages_run_fk FOREIGN KEY (run_id) REFERENCES runs(id) ON DELETE SET NULL;
CREATE UNIQUE INDEX IF NOT EXISTS runs_task_external ON runs(task_id, external_id) WHERE external_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS runs_created ON runs(created_at DESC);
CREATE INDEX IF NOT EXISTS runs_status ON runs(status);
CREATE INDEX IF NOT EXISTS runs_message ON runs(message_id);
CREATE INDEX IF NOT EXISTS runs_org ON runs(org_id, created_at DESC);

CREATE TABLE IF NOT EXISTS run_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  org_id BIGINT NOT NULL DEFAULT 1 REFERENCES orgs(id),
  run_id BIGINT NOT NULL REFERENCES runs(id) ON DELETE CASCADE,
  at TEXT NOT NULL,
  type TEXT NOT NULL,
  key TEXT,
  label TEXT NOT NULL,
  status TEXT,
  detail TEXT,
  metadata TEXT
);
CREATE INDEX IF NOT EXISTS run_events_run ON run_events(run_id, id);

CREATE TABLE IF NOT EXISTS events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  org_id BIGINT NOT NULL DEFAULT 1 REFERENCES orgs(id),
  platform TEXT,
  kind TEXT NOT NULL,
  title TEXT NOT NULL,
  body TEXT,
  link TEXT,
  read INTEGER NOT NULL DEFAULT 0,
  occurred_at TEXT NOT NULL,
  created_at TEXT NOT NULL,
  dedupe_key TEXT UNIQUE
);

CREATE TABLE IF NOT EXISTS platform_state (
  platform TEXT PRIMARY KEY,
  org_id BIGINT NOT NULL DEFAULT 1 REFERENCES orgs(id),
  session_status TEXT NOT NULL DEFAULT 'unknown',
  last_sync_at TEXT,
  last_ok_at TEXT,
  last_error TEXT,
  screenshot_path TEXT,
  meta TEXT
);

CREATE TABLE IF NOT EXISTS captures (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  org_id BIGINT NOT NULL DEFAULT 1 REFERENCES orgs(id),
  platform TEXT NOT NULL,
  url TEXT NOT NULL,
  method TEXT,
  status INTEGER,
  content_type TEXT,
  body TEXT,
  size INTEGER,
  captured_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS captures_platform ON captures(platform, captured_at DESC);

CREATE TABLE IF NOT EXISTS sync_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  org_id BIGINT NOT NULL DEFAULT 1 REFERENCES orgs(id),
  platform TEXT NOT NULL,
  started_at TEXT NOT NULL,
  finished_at TEXT,
  ok INTEGER,
  message TEXT,
  agents_found INTEGER,
  runs_found INTEGER,
  captures INTEGER
);

CREATE TABLE IF NOT EXISTS settings (
  key TEXT PRIMARY KEY,
  org_id BIGINT NOT NULL DEFAULT 1 REFERENCES orgs(id),
  value TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS policies (
  action TEXT PRIMARY KEY,
  org_id BIGINT NOT NULL DEFAULT 1 REFERENCES orgs(id),
  mode TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS approvals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  org_id BIGINT NOT NULL DEFAULT 1 REFERENCES orgs(id),
  run_id BIGINT REFERENCES runs(id) ON DELETE CASCADE,
  message_id BIGINT REFERENCES messages(id) ON DELETE SET NULL,
  action TEXT NOT NULL,
  provider TEXT,
  summary TEXT NOT NULL,
  detail TEXT,
  status TEXT NOT NULL DEFAULT 'pending',
  requested_at TEXT NOT NULL,
  decided_at TEXT,
  decided_by TEXT,
  reason TEXT
);
CREATE INDEX IF NOT EXISTS approvals_status ON approvals(status, requested_at DESC);

CREATE TABLE IF NOT EXISTS audit_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  org_id BIGINT NOT NULL DEFAULT 1 REFERENCES orgs(id),
  at TEXT NOT NULL,
  actor TEXT NOT NULL,
  action TEXT NOT NULL,
  target TEXT,
  detail TEXT,
  metadata TEXT
);
CREATE INDEX IF NOT EXISTS audit_at ON audit_log(at DESC);

CREATE TABLE IF NOT EXISTS sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  org_id BIGINT NOT NULL DEFAULT 1 REFERENCES orgs(id),
  token_hash TEXT NOT NULL UNIQUE,
  created_at TEXT NOT NULL,
  last_seen_at TEXT NOT NULL,
  expires_at TEXT NOT NULL,
  user_agent TEXT,
  ip TEXT
);

CREATE TABLE IF NOT EXISTS pairings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  org_id BIGINT NOT NULL DEFAULT 1 REFERENCES orgs(id),
  platform TEXT NOT NULL,
  code_hash TEXT NOT NULL UNIQUE,
  token_hash TEXT UNIQUE,
  status TEXT NOT NULL DEFAULT 'waiting',
  detail TEXT,
  created_at TEXT NOT NULL,
  expires_at TEXT NOT NULL,
  paired_at TEXT,
  finished_at TEXT,
  ip TEXT
);
CREATE INDEX IF NOT EXISTS pairings_platform ON pairings(platform, id DESC);

CREATE TABLE IF NOT EXISTS browser_sessions (
  id TEXT PRIMARY KEY,
  org_id BIGINT NOT NULL DEFAULT 1 REFERENCES orgs(id),
  blob TEXT NOT NULL,
  updated_at TEXT NOT NULL
);
`);
    },
  },
];

PG_MIGRATIONS.push({
  id: 101,
  name: "durable execution: idempotency, leases, cancellation, checkpoints",
  up: async (d) => {
    await d.exec(`
ALTER TABLE runs ADD COLUMN IF NOT EXISTS idempotency_key TEXT;
ALTER TABLE runs ADD COLUMN IF NOT EXISTS attempt INTEGER NOT NULL DEFAULT 0;
ALTER TABLE runs ADD COLUMN IF NOT EXISTS max_attempts INTEGER;
ALTER TABLE runs ADD COLUMN IF NOT EXISTS locked_by TEXT;
ALTER TABLE runs ADD COLUMN IF NOT EXISTS lease_expires_at TEXT;
ALTER TABLE runs ADD COLUMN IF NOT EXISTS cancel_requested INTEGER NOT NULL DEFAULT 0;
ALTER TABLE runs ADD COLUMN IF NOT EXISTS priority INTEGER;
ALTER TABLE runs ADD COLUMN IF NOT EXISTS queued_at TEXT;
ALTER TABLE runs ADD COLUMN IF NOT EXISTS checkpoint TEXT;
CREATE UNIQUE INDEX IF NOT EXISTS runs_idempotency ON runs(idempotency_key) WHERE idempotency_key IS NOT NULL;
`);
  },
});

PG_MIGRATIONS.push({
  id: 102,
  name: "outbox: the durable, ordered log of announced changes",
  up: async (d) => {
    await d.exec(`
CREATE TABLE IF NOT EXISTS outbox (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  org_id BIGINT NOT NULL DEFAULT 1 REFERENCES orgs(id),
  topic TEXT NOT NULL,
  payload TEXT,
  created_at TEXT NOT NULL,
  published_at TEXT
);
`);
  },
});

PG_MIGRATIONS.push({
  id: 103,
  name: "browser ops: interactive browser work requested by one process, done by another",
  up: async (d) => {
    await d.exec(`
CREATE TABLE IF NOT EXISTS browser_ops (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  org_id BIGINT NOT NULL DEFAULT 1 REFERENCES orgs(id),
  op TEXT NOT NULL,
  payload TEXT,
  status TEXT NOT NULL DEFAULT 'pending',
  result TEXT,
  created_at TEXT NOT NULL,
  finished_at TEXT
);
`);
  },
});

PG_MIGRATIONS.push({
  id: 104,
  name: "real user accounts; sessions know whose they are",
  up: async (d) => {
    await d.exec(`
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  org_id BIGINT NOT NULL DEFAULT 1 REFERENCES orgs(id),
  email TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'member',
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  last_login_at TEXT
);
ALTER TABLE sessions ADD COLUMN IF NOT EXISTS user_id BIGINT REFERENCES users(id) ON DELETE CASCADE;
`);
    // The single admin password becomes the first owner (legacy sha256: hash upgrades on login).
    const legacy = await d.get<{ value: string }>("SELECT value FROM settings WHERE key = 'admin_password_hash'");
    const none = ((await d.get<{ n: number }>("SELECT COUNT(*) AS n FROM users"))?.n ?? 0) === 0;
    if (legacy && none) {
      const ts = now();
      await d.run("INSERT INTO users (email, password_hash, role, created_at, updated_at) VALUES (?, ?, 'owner', ?, ?)", ["admin@local", `sha256:${legacy.value}`, ts, ts]);
    }
  },
});

PG_MIGRATIONS.push({
  id: 105,
  name: "workspaces: per-org uniqueness and account verification",
  up: async (d) => {
    // Uniqueness that was per-install becomes per-workspace: two workspaces may both hold a
    // "chatgpt" task or an "approval_mode" setting. Constraint names verified against a
    // fresh 100-104 database.
    await d.exec(`
ALTER TABLE settings DROP CONSTRAINT settings_pkey;
ALTER TABLE settings ADD PRIMARY KEY (org_id, key);
ALTER TABLE policies DROP CONSTRAINT policies_pkey;
ALTER TABLE policies ADD PRIMARY KEY (org_id, action);
ALTER TABLE platform_state DROP CONSTRAINT platform_state_pkey;
ALTER TABLE platform_state ADD PRIMARY KEY (org_id, platform);
ALTER TABLE browser_sessions DROP CONSTRAINT browser_sessions_pkey;
ALTER TABLE browser_sessions ADD PRIMARY KEY (org_id, id);
ALTER TABLE agent_profiles DROP CONSTRAINT agent_profiles_key_key;
CREATE UNIQUE INDEX agent_profiles_org_key ON agent_profiles(org_id, key);
ALTER TABLE tasks DROP CONSTRAINT tasks_platform_key_key;
CREATE UNIQUE INDEX tasks_org_platform_key ON tasks(org_id, platform, key);
ALTER TABLE events DROP CONSTRAINT events_dedupe_key_key;
CREATE UNIQUE INDEX events_org_dedupe ON events(org_id, dedupe_key) WHERE dedupe_key IS NOT NULL;
DROP INDEX runs_idempotency;
CREATE UNIQUE INDEX runs_idempotency ON runs(org_id, idempotency_key) WHERE idempotency_key IS NOT NULL;
CREATE INDEX outbox_org_id ON outbox(org_id, id);
ALTER TABLE users ADD COLUMN IF NOT EXISTS verified_at TEXT;
CREATE TABLE IF NOT EXISTS user_tokens (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  kind TEXT NOT NULL,
  token_hash TEXT NOT NULL UNIQUE,
  created_at TEXT NOT NULL,
  expires_at TEXT NOT NULL,
  used_at TEXT
);
`);
    // Accounts that exist predate verification; they must not be locked out.
    await d.run("UPDATE users SET verified_at = ? WHERE verified_at IS NULL", [now()]);
  },
});

PG_MIGRATIONS.push({
  id: 106,
  name: "workspaces fail closed: tenant rows must name their org",
  up: async (d) => {
    // With the DEFAULT 1 gone, an INSERT that forgets its workspace is a database error, not
    // a silent write into the founding workspace. Kept separate from 105 as a rollback lever.
    for (const t of ["agent_profiles", "conversations", "tasks", "messages", "runs", "run_events", "events", "platform_state", "captures", "sync_log", "settings", "policies", "approvals", "audit_log", "sessions", "pairings", "browser_sessions", "outbox", "browser_ops", "users"]) {
      await d.exec(`ALTER TABLE ${t} ALTER COLUMN org_id DROP DEFAULT`);
    }
  },
});

async function migratePg(d: SqlDriver): Promise<void> {
  await d.exec("CREATE TABLE IF NOT EXISTS schema_migrations (id INTEGER PRIMARY KEY, name TEXT NOT NULL, applied_at TEXT NOT NULL)");
  const applied = new Set((await d.all<{ id: number }>("SELECT id FROM schema_migrations")).map((r) => r.id));
  for (const m of PG_MIGRATIONS) {
    if (applied.has(m.id)) continue;
    await d.transaction(async () => {
      await m.up(d);
      await d.run("INSERT INTO schema_migrations (id, name, applied_at) VALUES (?, ?, ?)", [m.id, m.name, now()]);
    });
  }
}
